# Generated by Django 3.2.5 on 2021-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='term_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
