# Generated by Django 3.2.5 on 2021-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='term_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
